SHOW DATABASES;
USE test_db;
SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'test_db' ORDER BY TABLE_NAME;
SELECT '--- _prisma_migrations ---' AS section;
SELECT COUNT(*) AS migration_count FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'test_db' AND TABLE_NAME = '_prisma_migrations';
