SELECT 
  TABLE_NAME, 
  TABLE_ROWS,
  CREATE_TIME
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA='test_db'
ORDER BY TABLE_NAME;

SELECT COUNT(*) AS migration_count FROM test_db._prisma_migrations;
